### ISSUE TITLE
关于装好后使用过程中的一些问题咨询下

### ISSUE THREAD

**Issue by zddgitee** [zeroruka/Matebook-X-Pro-2019-OC#3]
感谢大佬提供的OC，小白2019买的matebook x pro 成功点亮，网卡9260 160mhz还是9560 160mhz 忘了，目前有点疑惑希望能解答下
1.wifi
开始安装的是menterey，但是wifi一输入密码连接就死机重启，类似这位
https://github.com/OpenIntelWireless/itlwm/issues/748
查看OC-kexts里有2个wifi驱动对应menterey和Ventura，尝试删除Ventura后反而进不去了。
是什么原因呢，有使用完整性检查啥的么?
2.蓝牙
wifi不能使用是硬伤，就更换成Ventura，这次wifi正常了，蓝牙又出问题，罗技鼠标无法连接，还好老的matebook有个usb-A，暂时用适配器连接鼠标。
https://github.com/OpenIntelWireless/IntelBluetoothFirmware/pull/446
说是有验证机制，大佬有用无线鼠标出现这情况么?
还是说2019的matebook，不能装太新的系统，最合适的是哪个版本呢?
3.扬声器
外放时右上角有2个播放设备可选，是否硬件机制上4喇叭无法同时播放?
4.Type-C外接显示器
修改了DVMT to 64mb，使用C-C接显示器无法4K-60HZ，之前win时可以4K-60HZ，
是要使用C-HDMI,C-DP的转接线才能4K-60HZ么?

**Comment by zeroruka** [comment]
1. 删除ventura驱动后需要编辑config.plist 里的驱动信息，要是删掉了kext但plist里还有ventura 驱动的信息那就启动不了。但是这应该不会影响monterey连不上wifi。可以试一下更新wifi的驱动。
2. 我的蓝牙没出现过问题，链接蓝牙手柄都是正常的，只不过有时可能发现不了设备，要一直等才能出现。要是还不行就更新一下驱动
3. 这个我不是很清楚
4. 我没有测试过4K-60HZ，但理论上是可以的，我不是很清楚为什么不行

**Comment by zddgitee** [comment]
感谢您的解答，目前各项问题都解决
1.wifi
config.plist貌似是默认加载Ventura的wifi驱动，使用另一台MAC的openCore Configurator编辑后，
并使用OpenIntelWireless/itlwm的最新驱动，在menterey正常使用。
2.蓝牙
Ventura新增的蓝牙验证机制导致部分设备无法连接例，如罗技鼠标，但无线键盘和airpods可以连接，
退回menterey自动解决此问题。
3.扬声器
使用MAC自带音频MIDI设置软件进行4扬声器组合，缺点是组合后无法调整系统音量，只能调整软件音量。
有其他EFI是直接组合在一起，证明是可行的。
4.Type-C外接显示器
修改DVMT后需要继续用propertree去修改config.plist，
移除里面缓冲帧的“framebuffer-fbmem”，“framebuffer-stolenmem”，“framebuffer-unifiedmem”
不清楚会造成其他什么影响，但可以C-C接显示器4K-60HZ了。
